* Duration
From 24 Sep 2020 to 

* Content
1. [[#day-91-se][Day 91: Towards Accurate Duplicate Bug Retrieval using Deep Learning Techniques]]
2. [[#day-92-se][Day 92: Deeper Text Understanding for IR with Contextual Neural Language Modeling]]

* Day 91: SE
- *Title*: Towards Accurate Duplicate Bug Retrieval using Deep Learning Techniques
- *Year*: 2017
- *Proc*: ICSME

The following content is referred from [1]
** Problem
duplicate bug detection

** Method
They proposed a retrieval and classification model using Siamese Convolution Neural Networks (CNN) and Long Short Term Memory (LSTM) for accurate detection and retrieval of duplicate and similar bugs.

- Unsupervised Approaches: Typical strategy used here is to create a numerical similarity scoring function like cosine similarity.
- 
** Result
They report an accuracy close to 90% and recall rate close to 80%, which makes possible the practical use of such a system.

** Future work
1. Elaborate experimentation is required to train the model effectively, using techniques like batch normalization and various other tweaks. Hyperparameter tuning is done only to a certain extent, more can be done in this regard to improve the results further. The training data is also less for a model of this scale, more training data has to be consolidated for various domains (across projects) to train the model.
2. Incorporating attention mechanism: The currently the model does not have any attention mechanism. Incorporating an appropriate attention mechanism to automatically learn the part of the bug that has to be attended and prioritized, while processing a certain part of duplicate and non duplicate bug, will deﬁnitely yield better results.
3. Other models: Attempting models like Tree-LSTMs for the encodings of single sentence bug descriptions compared to bi-LSTMs. Paragraph vectors and document vectors 5 for the original duplicate/similar bug matching problem should be explored.

* Day 92: NLP
- *Title*: Deeper Text Understanding for IR with Contextual Neural Language Modeling
- *Year*: 2019
- *Proc*: SIGIR

The following content is referred from [2]
** Problem
leveraging contextual neural language model, BERT, to provide deeper text understanding for IR.

Different from traditional word embeddings, they are contextual – the representation of a word is a function of the entire input text, with word dependencies and sentence structures taken into consideration.

** Method
We adopt a simple passage level approach for document retrieval. We split a document into overlapping passages. The neural ranker predicts the relevance of each passage independently. document score is the score of the first passage (BERT-FirstP), the best passage (BERT-MaxP), or the sum of all passage scores (BERT-SumP). For training, passage-level labels are not available in this work. We consider all passages from a relevant document as relevant and vice versa. When the document title is available, the title is added to the beginning of every passage to provide context.

** Result
Compared to bag-of-words retrieval models, the contextual language model can better leverage language structures, bringing large improvements on queries written in natural languages.


* Day 93: SE
- *Title*: Automatically Repairing Programs Using Both Tests and Bug Reports
- *Year*: 2020
- *Source*: ArXiv

The paper can be accessed from https://arxiv.org/pdf/2011.08340.pdf
** Problem
*** Important Concepts
1. fault localization (FL)
2. spectrum-based (SBFL): test executions
3. information-retrieval (IRFL): using bug reports

They developed Blues, a new statement-level IRBL technique that uses bug reports, and an unsupervised approach to localize defects.

Three steps for automated program repair tools:
1. Identifying the location of bug
2. Producing candidate patches
3. Validating those patches

This work focuses on fault localization.

To the best of our knowledge, only two repair tools, R2Fix and iFixR, use IRFL, which ranks suspicious program elements based on their similarity with bug reports.

** Method
They develop RAFL (Rank-Aggregation-Based Fault Localization), a novel FL approach that combines multiple FL techniques.

RAFL measures the similarity of the two ranked lists using the Spearman footrule distance and runs the cross-entropy Monte Carlo algorithm to produce a super list of top-k statements while maximizing the similarity to the individual lists.


We formulate the problem of combining multiple FL techniques as a rank aggregation (RA) problem.

We propose to use RA algorithms for combining multiple FL techniques’ ranked lists of suspicious statements.

** Result

** Future Work


* Day 94: SE
- *Title*: iFixR: Bug Report driven Program Repair
- *Year*: 2019
- *Source*: FSE'19

The paper can be accessed from https://arxiv.org/pdf/1907.05620.pdf
** Problem
** Method
** Result
** Future Work

* Reference
1. Deshmukh, J., Podder, S., Sengupta, S., & Dubash, N. (2017, September). Towards accurate duplicate bug retrieval using deep learning techniques. In 2017 IEEE International conference on software maintenance and evolution (ICSME) (pp. 115-124). IEEE.

2. Piwowarski, B., Chevalier, M., Gaussier, E., Maarek, Y., Nie, J.-Y., Scholer, F., Dai, Z., & Callan, J. (2019). Deeper Text Understanding for IR with Contextual Neural Language Modeling. ArXiv, 985–988. https://doi.org/10.1145/3331184.3331303